feat(customerio): add beta API and support update campaign action
trendhim/go-customerio pull request #1
Opened 2021-11-05 19:22 UTC by Glagnar

A copy of the API client, with support for beta functionality.

2021-11-05 19:24 UTC, Glagnar commented
/assign @Multiply

2021-11-05 19:29 UTC, Multiply requested changes

2021-11-05 19:29 UTC, Multiply commented on go.mod
> +module github.com/trendhim/go-customerio
We shouldn't modify this.

2021-11-06 07:17 UTC, Glagnar commented on go.mod
> +module github.com/trendhim/go-customerio
Cool - wasn't sure how we were going to do this.

2021-11-06 10:31 UTC, Multiply approved these changes

2021-11-06 10:31 UTC, merged